name: fastai2
channels:
- fastai
- pytorch
- defaults
dependencies:
- appmode
- jupyter
- fastai
- pytorch>=1.3.0
- torchvision>=0.5
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress>=0.1.22
- pillow
- python>=3.6
- pip
- pip:
    - fastai2
    - voila
    - pillow<7
    - packaging
    - ipywidgets==7.5.1
- scikit-learn
- scipy
- spacy

